### PR TITLE
Empty cqueue shouldn't hang

### PR DESCRIPTION
**Pull request by daurnimator**
An empty queue waits forever: `require"cqueues".new():loop()`

### CODE REVIEW

**Comment by wahern** [comment]
1) The loop bug is arguably in cqueues.loop. It calls step once before checking cqueues:empty. I think originally I just assumed that if somebody called :step on an empty coroutine that was their problem.

2) Technically an event _can_ come:

```lua
local outer = cqueues.new()
local inner = cqueues.new()

outer:wrap(function ()
    print("# controllers:", inner:count())
    print("calling step")
    inner:step()
    print("step completed")
end)

outer:wrap(function ()
    cqueues.sleep(2)
    inner:wrap(function ()
        print("running in inner loop")
    end)
end)

outer:loop()
```

3) This begs the question of what to do. My intention was for loop to exit when there were no more coroutines. The alert feature came later. But now with the alert feature it _can_ make sense for loop (and necessarily step) to poll even when there are no coroutines attached. I suppose it should be made an option, with the default behavior to exit.

**Comment by daurnimator** [comment]
> 2) Technically an event can come:

That still works?

> 3) This begs the question of what to do. My intention was for loop to exit when there were no more coroutines. The alert feature came later. But now with the alert feature it can make sense for loop (and necessarily step) to poll even when there are no coroutines attached. I suppose it should be made an option, with the default behavior to exit.

It sounds like the only cases are when you `:step` or `:loop` from inside a running cqueues thread?
Isn't this already taken care of by the `running` branch of the lua wrapper of `:step`?

**Comment by daurnimator** [comment]
I think this needs to be backed out...

@torhve reported an issue to me when using cqueues from a lua-ev mainloop. If the managed cqueue becomes empty, it ends up in an infinite loop.

To counter my own example from the original report, should it be possible to wake up an empty sleeping loop from another thread:
```lua
local cq = require"cqueues".new();
give_to_another_thread(cq:pollfd())
cq:loop()
```

**Comment by daurnimator** [comment]
> I think this needs to be backed out...
> 
> @torhve reported an issue to me when using cqueues from a lua-ev mainloop. If the managed cqueue becomes empty, it ends up in an infinite loop calling step/epoll_wait.

If a cqueues becomes empty it shouldn't have `:step` called on it. The solution is to add a check for `:empty()`
 
> To counter my own example from the original report: should it be possible to wake up an empty sleeping loop from another thread?
> 
> local cq = require"cqueues".new()
> give_to_another_thread(cq:pollfd())
> cq:loop()

This counter example isn't valid: the cqueues pollfd isn't for passing to another thread.

------------------------------------

Possibly instead, calling `:step` on an empty cqueue should *error*.

**Comment by daurnimator** [comment]
Further investigation has revealed that a cqueue is polling readable due to a `tryalert` that was already resolved.

> Possibly instead, calling :step on an empty cqueue should error.

Without calling `:step()` there is no way to calm the alerted kqueue.

To fix, this, we can allow `:step` on an empty cqueue to be equivalent to a 0 timeout.
whitespace-less diff:
```diff
diff --git a/src/cqueues.c b/src/cqueues.c
index e0a3157..4d79eca 100644
--- a/src/cqueues.c
+++ b/src/cqueues.c
@@ -2239,8 +2239,7 @@ static int cqueue_step(lua_State *L) {
 		return luaL_error(L, "cannot step live cqueue");
 	}
 
-	if (Q->thread.count) {
-		if (LIST_EMPTY(&Q->thread.pending)) {
+	if (Q->thread.count && LIST_EMPTY(&Q->thread.pending)) {
 		timeout = mintimeout(luaL_optnumber(L, 2, NAN), cqueue_timeout_(Q));
 	} else {
 		timeout = 0.0;
@@ -2273,7 +2272,6 @@ static int cqueue_step(lua_State *L) {
 	default:
 		goto oops;
 	}
-	}
 
 	lua_pushboolean(L, 1);
 
```

**Comment by wahern** [comment]
Code committed along with regression test. I discovered a curious behavior with BSD kqueue. See [the commit note](https://github.com/wahern/cqueues/commit/80e33bc4f25fd1f6c117527393db9afd5ed20c20#diff-5b0307b88f22b998ff1c42a002a1f3f2R64). I'm having trouble imaging a scenario where the kqueue behavior might cause trouble, but it's something to keep in mind. It could also be a performance issue, or just plain annoying. A possible remedy/mitigation is for cqueue_step to iterate twice every invocation, at least for kqueue environments.

**Comment by daurnimator** [comment]
> I discovered a curious behavior with BSD kqueue. See the commit note. I'm having trouble imaging a scenario where the kqueue behavior might cause trouble, but it's something to keep in mind. It could also be a performance issue, or just plain annoying. A possible remedy/mitigation is for cqueue_step to iterate twice every invocation, at least for kqueue environments.

This could already happen (on any platform) if there were more than `KPOLL_MAXWAIT` ready.
If any issues poke their heads up, they will have already existed. See also #42

**Comment by wahern** [comment]
On Wed, Jun 01, 2016 at 07:37:01PM -0700, daurnimator wrote:
> > I discovered a curious behavior with BSD kqueue. See the commit note. I'm having trouble imaging a scenario where the kqueue behavior might cause trouble, but it's something to keep in mind. It could also be a performance issue, or just plain annoying. A possible remedy/mitigation is for cqueue_step to iterate twice every invocation, at least for kqueue environments.
> 
> This could already happen (on any platform) if there were more than
> `KPOLL_MAXWAIT` ready. If any issues poke their heads up, they will have
> already existed. See also #42
> 

Yes, and also if there was simply an event that was always polling as true
(e.g. socket.dup(io.open("/dev/zero")), or if there was a ping-pong between
two queues. I was just thinking of cases like the test case where you know
for a fact that none of those scenarios is present but you still got this
unexpected behavior.

**Pull request merged**
